var car = 'BMW';
console.log("Is car == 'BMW'? I predict True.");
console.log(car == 'BMW');
console.log("\nIs 2 > 1? I predict True");
console.log(2 > 1);
var city = 'Lahore';
console.log("\nIs city != 'Karachi'? I predict True");
console.log(city != 'Karachi');
console.log("\nIs 5*2==10? I predict True");
console.log(5 * 2 == 10);
console.log("\nIs 6/2==3? I predict True");
console.log(6 / 2 == 3);
console.log("\nIs 2 < 1? I predict False");
console.log(2 < 1);
console.log("\nIs 10/2==3? I predict False");
console.log(10 / 2 == 3);
console.log("\nIs 10-2==9? I predict False");
console.log(10 - 2 == 9);
var Fruit = 'Apple';
console.log("\nIs Fruit == 'Mangoo'? I predict False");
console.log(Fruit == 'Mangoo');
var age = 20;
console.log("\nIs age != 20? I predict False");
console.log(age != 20);
