var car = 'Audi';
console.log("Is car == 'Audi'? I predict True.");
console.log(car == 'Audi');
console.log("Is car != 'Audi'? I predict False.");
console.log(car != 'Audi');
console.log("Is car.toLowerCase() == 'Audi'? I predict False.");
console.log(car.toLowerCase() == 'Audi');
var num = 5;
console.log("\nIs num > 10? I predict False");
console.log(num > 10);
console.log("\nIs num < 10? I predict True");
console.log(num < 10);
console.log("\nIs num >= 10? I predict False");
console.log(num >= 10);
console.log("\nIs num <= 10? I predict True");
console.log(num <= 10);
console.log("\nIs num < 10 and num % 2 == 0? I predict False");
console.log(num < 10 && num % 2 == 0);
console.log("\nIs num < 10 or num % 2 == 0? I predict True");
console.log(num < 10 || num % 2 == 0);
var list = [1, 2, 3, 4, 5];
console.log("\nIs 10 is in list? I predict False");
console.log(10 in list);
console.log("\nIs 10 is in list? I predict False");
console.log(2 in list);
